imports:
  # - { resource: ./services/*.yaml }

parameters:

services:
  _defaults:
    autoconfigure: true
    autowire: true

  bitbirddev\TwigComponentsBundle\:
    resource: "../src/*"
    exclude:
      - "../src/{DependencyInjection,Entity,Tests,Kernel.php}"

  # bitbirddev\TwigComponentsBundle\Twig\Components\MediaPlayerComponent: ~
  # bitbirddev\TwigComponentsBundle\MediaType\Matchers\DataObjectMatcher:
  #   tags: ["mediatype.matcher"]
  bitbirddev\TwigComponentsBundle\MediaType\HandlerCollection:
    arguments:
      $handlers: !tagged_iterator mediatype.handler
